### ISSUE TITLE
Release ruby-runtime 0.12

### ISSUE THREAD

**Issue by yyuu** [jenkinsci/jenkins.rb#91]
Please release `ruby-runtime` 0.12 from SHA1@4bb3f9e5fe933f8ca36c72b94183e4ff61690e19. This version should fix following problems on both Jenkins <=1.518 and >=1.519.
- [JENKINS-18528](https://issues.jenkins-ci.org/browse/JENKINS-18528)
- #86

The SNAPSHOT artifact has been deployed to maven.jenkins-ci.org. Please report here if you've met problem with this.

http://maven.jenkins-ci.org/content/repositories/snapshots/org/jenkins-ci/plugins/ruby-runtime/0.12-SNAPSHOT/ruby-runtime-0.12-20130704.105209-1.hpi

**Comment by JakubMucha** [comment]
Caused by: java.nio.file.FileSystemException: C:\Program Files (x86)\Jenkins\plugins\ruby-runtime\WEB-INF\lib\classes.jar

same error as above
